# Resume Training Configuration
# This config demonstrates how to resume training from checkpoints

model:
  name: "xception_deepfake"
  type: "file"
  path: "/content/drive/MyDrive/trained/xception.py"
  class_name: "Xception"
  architecture: null
  pretrained: false
  
  num_classes: 2
  model_args:
    num_classes: 2
  
  adapter: auto

data:
  name: "DeepfakeDetection"
  type: "class_folders"
  train_path: "/content/drive/MyDrive/train"
  val_path: "/content/drive/MyDrive/validation"


  class_folders:
    real: "real"
    fake: "fake"
  
  max_samples: 5
  class_mapping:
    real: 0
    fake: 1
  
  img_size: 299

  augmentation:
    enabled: true
    horizontal_flip: true
    rotation: 10
    color_jitter: true
    normalize: true
    normalization_mean: [0.5, 0.5, 0.5]
    normalization_std: [0.5, 0.5, 0.5]

training:
  epochs: 10                               # Continue for more epochs
  learning_rate: 0.001
  optimizer: "adam"
  weight_decay: 0.0001
  
  scheduler: "cosine"
  scheduler_params:
    eta_min: 0.00001
  
  # Resume from checkpoint
  resume_from_checkpoint: "checkpoint_epoch_5.pth"
  # Alternative options:
  # resume_from_checkpoint: "./training_output/xception_deepfake/best_checkpoint.pth"
  # resume_from_checkpoint: "./training_output/xception_deepfake/checkpoint_epoch_5.pth"

output:
  output_dir: "/content/drive/MyDrive/trained/training_output"
  experiment_name: "xception_deepfake"

  # Checkpoint saving behavior for continuation
  save_best_only: false               # ✅ USED: Save regular checkpoints
  save_last: true                     # ✅ USED: Save final checkpoint
  save_best_model: true               # ✅ USED: Track and save best model
  track_best_metric: "val_accuracy"   # ✅ USED: Metric to track for "best"
  
  # Checkpoint management
  keep_recent_checkpoints: 5          # ✅ USED: Keep last 5 checkpoints
  weight_format: "pth"         

device: "auto"
seed: 42

description: "Resume Xception training from checkpoint"
tags: ["xception", "deepfake-detection", "resume-training"]


