# Advanced Augmentation Configuration Example
# Demonstrates all supported augmentation techniques

model:
  name: "advanced_aug_model"
  type: "torchvision"
  architecture: "resnet50"
  pretrained: true
  num_classes: 10

data:
  name: "comprehensive_augmentation_dataset"
  type: "class_folders"
  real_path: "data/real"
  fake_path: "data/fake"
  img_size: 224
  batch_size: 32
  
  # Comprehensive augmentation configuration showing ALL options
  augmentation:
    enabled: true
    
    # Basic augmentations
    horizontal_flip: true
    vertical_flip: false               # Usually not recommended for natural images
    rotation: 15                       # Degrees
    
    # Legacy color jitter (all-in-one)
    color_jitter: false                # Disable to use individual controls
    
    # Individual color controls (used when color_jitter: false)
    brightness: 0.1                    # Brightness variation
    contrast: 0.1                      # Contrast variation  
    saturation: 0.1                    # Saturation variation
    hue: 0.05                          # Hue variation
    
    # Advanced augmentations
    gaussian_blur: true                # Random blur
    blur_kernel_size: 5                # Blur kernel size (must be odd)
    blur_sigma: [0.1, 1.5]            # Blur intensity range
    
    # Cropping options
    random_crop: false                 # Use random resized crop instead of resize
    random_crop_size: 200              # Crop size before resize
    center_crop: false                 # For validation (usually false)
    center_crop_size: 224              # Center crop size
    
    # Normalization
    normalize: true
    normalization_mean: [0.485, 0.456, 0.406]
    normalization_std: [0.229, 0.224, 0.225]

training:
  epochs: 50
  learning_rate: 0.001
  optimizer: "adamw"
  scheduler: "cosine"

output:
  output_dir: "training_output"
  experiment_name: "advanced_augmentation"
  save_best_only: true

device: "auto"
seed: 42
