# Default Configuration for Train System
# Minimal working configuration

# Model configuration
model:
  name: "default_model"
  type: "torchvision"
  architecture: "resnet18"
  pretrained: true
  num_classes: 2
  img_size: 224

# Dataset configuration  
data:
  name: "default_dataset"
  type: "class_folders"
  train_path: "data/train"
  val_path: "data/val"
  batch_size: 32
  img_size: 224
  num_workers: 4
  
  # Automatic train/val splitting
  auto_split_enabled: true
  train_split_ratio: 0.8
  split_seed: 42
  
  # Data augmentation
  augmentation:
    normalize: true
    random_horizontal_flip: true
    random_rotation: 10

# Training configuration
training:
  epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  
  # Training behavior
  save_frequency: 5
  log_interval: 10

# Output configuration
output:
  output_dir: "training_output"
  experiment_name: "default_experiment"
  save_best_only: true
  save_last: true

# System settings
device: "auto"
seed: 42
description: "Default training configuration"
